### ISSUE TITLE
프로젝트 생성

### ISSUE THREAD

**Issue by Jonny-Cho** [Jonny-Cho/commerce-api-gateway#1]
![image](https://user-images.githubusercontent.com/24591642/149132480-bdb80082-ad6e-4f0e-97c6-a12b8f968c80.png)

![image](https://user-images.githubusercontent.com/24591642/149132883-379e8331-6a4d-43bf-ad46-6809d99ad728.png)

application.yml로 수정

```
server:
  port: 8000

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka #service discovery 주소

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: http://localhost:8082/
          predicates:
            - Path=/second-service/**
```

api gateway가 있는데 service discovery는 왜필요하지?
https://futurecreator.github.io/2018/10/18/service-discovery-in-microservices/

> 클라우드에서 인스턴스는 동적으로 할당되기 때문에 IP주소나 포트 정보가 정해지지 않은 데다가 오토스케일링도 일어나고 중지되고 복구되면서 네트워크 위치가 계속해서 바뀌게 됩니다.
> 따라서 클라이언트나 API 게이트웨이가 호출할 서비스를 찾는 매커니즘이 필요하고 이를 서비스 디스커버리(Service Discovery)라고 합니다

![image](https://user-images.githubusercontent.com/24591642/149134421-db6a0724-6fc1-4d09-872f-2b78be9d26d9.png)

tomcat 아니고
netty(비동기 내장서버)로 동작함
